[package]
name = "binominal_tree_model"
version = "0.1.0"
edition = "2024"

[[bench]]
name = "bench"
harness = false

[dependencies]
criterion = { version = "0.5.1", features = ["html_reports"] }
hashbrown = { version = "0.15.2", features = ["rayon"] }
itertools = "0.14.0"
num = "0.4.3"
rayon = "1.10.0"

[profile.release-with-debug]
inherits = "release"
debug = true

[rust]
debuginfo-level = 1

[build]
rustflags = ["-C", "symbol-mangling-version=v0"]
