[package]
name = "binomial-tree-macro"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
syn = {version = "2.0.100", features = ["full"]}
proc-macro2 = "1.0.94"
quote = "1.0.40"
itertools = "0.14.0"
